# generated by configure / remove this line to disable regeneration
prefix="/usr"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/home/arun/Desktop/TakeDownHSS/CodeQL/RealWorldRepos/libextractor/src/.libs"
sysconfdir="${prefix}/etc"
includedir="/home/arun/Desktop/TakeDownHSS/CodeQL/RealWorldRepos/libextractor/."
package="libextractor"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "libextractor"
;; --help) pkg-config --help ; echo Buildscript Of "Metadata extraction library"
;; --modversion|--version) echo "1.6"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-lextractor"
       :
;; --cflags) echo -I${includedir} ""
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
